set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
"set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
"Plugin 'VundleVim/Vundle.vim'

" install youcompleteme plugin 
"Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
"call vundle#end()            " required
"filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on



" put a color scheme here
color elflord

" enable syntax processing
syntax enable
  
" 
" remap escape to something on home row
imap jj <Esc>
imap Ctrl+[ <Esc>

" set tabs to equal 4 spaces. present tabs as spaces.
set tabstop=4
set softtabstop=4
set expandtab
set autoindent
set smartindent

" show relative line numbers AND the absolute line number of
" the line the cursor is on.
set relativenumber
set number

" show the current line the cursor is on. Show a marker at the 100 char width
set cursorline
set cc=80

" show matching brackets/parens/curly
set showmatch

" improving vim search
set incsearch
set hlsearch

" Use a mouse everywhere
set mouse=a

" the following commands allow the movement keys to move accross visual lines
" and not skip rows based off line number
nnoremap j gj
nnoremap k gk
nnoremap <silent><F12> :so $MYVIMRC <cr>

" remove rule to allow for status line mods
set noruler
set laststatus=2

" status line highlight function
function! HighlightSearch()
  if &hls
    return 'H'
  else
    return ''
  endif
endfunction

" status line mods
set statusline=
set statusline+=%7*\[%n]                                  "buffernr
set statusline+=%1*\ %<%F\                                "File+path
set statusline+=%2*\ %y\                                  "FileType
set statusline+=%3*\ %{''.(&fenc!=''?&fenc:&enc).''}      "Encoding
set statusline+=%3*\ %{(&bomb?\",BOM\":\"\")}\            "Encoding2
set statusline+=%4*\ %{&ff}\                              "FileFormat (dos/unix..) 
set statusline+=%5*\ %{&spelllang}\%{HighlightSearch()}\  "Spellanguage & Highlight on?
set statusline+=%8*\ %=\ row:%l/%L\ (%03p%%)\             "Rownumber/total (%)
set statusline+=%9*\ col:%03c\                            "Colnr
set statusline+=%0*\ \ %m%r%w\ %P\ \                      "Modified? Readonly? Top/bot.
